### ISSUE TITLE
I have no idea

### ISSUE THREAD

**Issue by CarterSullivan** [nwithan8/Arca#24]
I'm running Debian 10, having all sorts of errors:
`Loading media_server.plex.plex...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/manager/media_server/plex/plex.py", line 12, in <module>
    import media_server.plex.plex_api as px
  File "/opt/manager/media_server/plex/plex_api.py", line 13, in <module>
    plex = PlexServer(settings.PLEX_SERVER_URL[0], settings.PLEX_SERVER_TOKEN[0])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bot.py", line 25, in <module>
    bot.load_extension(path)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'media_server.plex.plex' raised an error: IndexError: list index out of range`
It does that with both the plex and plex_manager cog. Please help, thanks. brand new to this and I don't know how anything works, so I apologize.

**Comment by CarterSullivan** [comment]
It decided to not format that as code. Odd
